PrestaShop/kanbanbot

src/PullRequestDashboard/Application/Command/MovePullRequestCardToColumnByApprovalCountCommand.php
src/PullRequestDashboard/Application/CommandHandler/MovePullRequestCardToColumnByApprovalCountCommandHandler.php
src/PullRequestDashboard/Domain/Aggregate/Column.php
src/PullRequestDashboard/Domain/Aggregate/PullRequest.php
src/PullRequestDashboard/Domain/Aggregate/PullRequestCard.php
src/PullRequestDashboard/Infrastructure/Adapter/GraphqlGithubPullRequestCardRepository.php
src/PullRequestDashboard/Infrastructure/Adapter/InMemoryPullRequestPullRequestCardRepository.php
src/Shared/Command/OnGithubEventCommand.php
src/Shared/Factory/CommandFactory/CommandFactory.php
src/Shared/Factory/CommandFactory/Strategy/PullRequestApprovedStrategy.php
src/Shared/Factory/CommandFactory/Strategy/PullRequestLabeledStrategy.php
src/Shared/Factory/CommandFactory/Strategy/RequestChangesStrategy.php
src/Shared/Listener/GithubEventListener.php
tests/PullRequestDashboard/Application/CommandHandler/MovePullRequestCardToColumnByApprovalCountHandlerTest.php
tests/PullRequestDashboard/Application/CommandHandler/MovePullRequestCardToColumnByLabelHandlerTest.php
tests/PullRequestDashboard/Infrastructure/Adapter/GraphqlGithubPullRequestCardRepositoryTest.php
tests/Shared/Command/OnGithubEventCommandTest.php

| Description?      | Kanbanbot listen to pull request review approvals

Kanbanbot listen to pull request review approvals

---

composer.json
composer.lock

| Description?      | Upgrade to symfony 6.3

Upgrade to symfony 6.3

---

config/services.php
src/Shared/Webhook/GithubWebhookParser.php
tests/PullRequest/Infrastructure/Adapter/RestGithubCommitterRepositoryTest.php
tests/PullRequestDashboard/Infrastructure/Adapter/RestGithubCommitterRepositoryTest.php
tests/Shared/Webhook/GithubWebhookTest.php

| Description?      | Check payload signature from webhook
| Sponsor company   |

Check payload signature from webhook

---

composer.lock
tests/PullRequest/Application/CommandHandler/RequestChangesCommandHandlerTest.php
tests/PullRequest/Infrastructure/Adapter/RestGithubCommitterRepositoryTest.php
tests/PullRequestDashboard/Infrastructure/Adapter/RestGithubCommitterRepositoryTest.php

| Description?      | Librairies bumping
| Type?             | improvement / new feature

Composer update

---

config/services.php

| Description?      | Bump `v1.2.0`

Bump v1.2.0

---

.env
.github/workflows/php.yml
composer.json

| Description?      | Add php checking on ci

Add php checking on ci

---

config/services.php
src/Shared/Infrastructure/Factory/CommandFactory/CommandFactory.php
src/Shared/Infrastructure/Factory/CommandFactory/ExclusionStrategyInterface.php
src/Shared/Infrastructure/Factory/CommandFactory/Strategy/Command/PullRequestApprovedStrategy.php
src/Shared/Infrastructure/Factory/CommandFactory/Strategy/Command/PullRequestClosedStrategy.php
src/Shared/Infrastructure/Factory/CommandFactory/Strategy/Command/PullRequestLabeledStrategy.php
src/Shared/Infrastructure/Factory/CommandFactory/Strategy/Command/PullRequestMergedStrategy.php
src/Shared/Infrastructure/Factory/CommandFactory/Strategy/Command/PullRequestReadyForReviewStrategy.php
src/Shared/Infrastructure/Factory/CommandFactory/Strategy/Command/PullRequestReopenedStrategy.php
src/Shared/Infrastructure/Factory/CommandFactory/Strategy/Command/RequestChangesStrategy.php
src/Shared/Infrastructure/Factory/CommandFactory/Strategy/Exclusion/ExcludedLabelsStrategy.php
src/Shared/Infrastructure/Factory/CommandFactory/Strategy/Exclusion/ExcludedRepositoryStrategy.php
tests/Shared/Infrastructure/Webhook/GithubWebhookTest.php

| Description?      | Add Closed / Merged / Opened / Ready for review / Reopened actions
| Deprecations?     | yes (Don't use Github Workflows anymore for theses actions)
| Fixed ticket?     | Fixed #22 
**For Ready for review and Opened:**
- Only if the repository isn't excluded.
- Only if labels aren't excluded.

Manage simple actions

---

config/services.php

| Description?      | Bump to `1.3.0`

Bump to `1.3.0` version

---

tests/Shared/Infrastructure/Webhook/GithubWebhookTest.php

| Description?      | Fix GithubWebhookTest for CI:<br>- Clean output of E2E tests<br>- Real tests on exceptions with client requests.
| How to test?      | CI must be 🟢
Before this PR:
After this PR:

Fix GithubWebhookTest for CI

---

.github/workflows/php.yml
.gitignore
composer.json
composer.lock
phpstan.dist.neon
symfony.lock

| Description?      | Add CS Fixer in github actions
| Type?             | improvement 
| Fixed ticket?     | N/A
| Sponsor company   | PrestaShop SA 
| How to test?      | CI is 💚

Add CS Fixer in github actions

---

config/services.php

| Description?      | Bump version number to 1.4.0 as https://github.com/PrestaShop/kanbanbot/pull/34 is a new feature

Bump version number to 1.4.0

---

src/PullRequest/Application/Command/WelcomeNewContributorCommand.php
src/PullRequest/Application/CommandHandler/WelcomeNewContributorCommandHandler.php
src/PullRequest/Domain/Gateway/PullRequestRepositoryInterface.php
src/PullRequest/Infrastructure/Adapter/InMemoryPullRequestRepository.php
src/PullRequest/Infrastructure/Adapter/RestPullRequestRepository.php
src/Shared/Domain/Gateway/CommitterRepositoryInterface.php
src/Shared/Infrastructure/Adapter/InMemoryCommitterRepository.php
src/Shared/Infrastructure/Adapter/RestGithubCommitterRepository.php
src/Shared/Infrastructure/Factory/CommandFactory/Strategy/Command/PullRequestReadyForReviewStrategy.php
templates/pr_comments/welcome.html.twig
tests/Shared/Infrastructure/Adapter/RestGithubCommitterRepositoryTest.php
tests/Shared/Infrastructure/Webhook/GithubWebhookTest.php

| Description?      | Comment the new PR if author hasn't already commit officially in repository.
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/34270
| How to test?      | 1. Create a new PR with new github account.<br>2. Check Jarvis post a comment to welcome this new contributor.<br>3. Create a new PR with a github account that already commit in repository. <br>4. Check Jarvis don't post a comment to welcome this contributor.

Add Welcome comment for new contributor

---

config/services.php

| Description?      | Bump to `1.5.0` version
| How to test?      | Nothing to test here.

Bump version to 1.5.0

---

composer.json
composer.lock
config/packages/validator.yaml
src/PullRequest/Application/Command/CheckMilestoneCommand.php
src/PullRequest/Application/Command/CheckTableDescriptionCommand.php
src/PullRequest/Application/CommandHandler/CheckMilestoneCommandHandler.php
src/PullRequest/Application/CommandHandler/CheckTableDescriptionCommandHandler.php
src/PullRequest/Domain/Aggregate/PullRequest/PullRequest.php
src/PullRequest/Domain/Aggregate/PullRequest/PullRequestDescription.php
src/PullRequest/Domain/Gateway/PullRequestRepositoryInterface.php
src/PullRequest/Infrastructure/Adapter/InMemoryPullRequestRepository.php
src/PullRequest/Infrastructure/Adapter/RestPullRequestRepository.php
src/Shared/Infrastructure/Factory/CommandFactory/Strategy/Command/PullRequestEditedStrategy.php
src/Shared/Infrastructure/Factory/CommandFactory/Strategy/Command/PullRequestReadyForReviewStrategy.php
symfony.lock
templates/pr_comments/missing_milestone.html.twig
templates/pr_comments/table_errors.html.twig
tests/PullRequest/Application/CommandHandler/CheckMilestoneCommandHandlerTest.php
tests/PullRequest/Application/CommandHandler/CheckTableDescriptionCommandHandlerTest.php
tests/PullRequest/Application/CommandHandler/WelcomeNewContributorCommandHandlerTest.php
tests/Shared/Infrastructure/Webhook/GithubWebhookTest.php

| Description?      | Add `CheckTableDescription` and `CheckMilestone` commands for:<br>- Check the table description of PRs and comment this PR with errors.<br>- If `QA ✔` and the PR has no milestone, we comment this PR with an suggestion to add milestone.<br><br>*bonus:* add missing tests for welcome new contributors.
| Fixed ticket?     | Fixes [#34269](https://github.com/PrestaShop/PrestaShop/issues/34269), Fixes [#34274](https://github.com/PrestaShop/PrestaShop/issues/34274), Fixes [#34272](https://github.com/PrestaShop/PrestaShop/issues/34272), Fixes …

CheckTableDescription & CheckMilestone

---

src/PullRequest/Application/CommandHandler/WelcomeNewContributorCommandHandler.php
tests/PullRequest/Application/CommandHandler/WelcomeNewContributorCommandHandlerTest.php

| Description?      | Ignore dependabot PR when Welcoming new contributors
| Type?             | bug fix

Ignore dependabot PR when Welcoming new contributors

---

src/PullRequest/Domain/Aggregate/PullRequest/PullRequestDescription.php
tests/PullRequest/Application/CommandHandler/CheckTableDescriptionCommandHandlerTest.php

| Description?      | Fix UI Tests template after [#36329](https://github.com/PrestaShop/PrestaShop/pull/36329)
| Type?             | bug fix

Fix UI Tests template after #36329

---

config/services.php

| Description?      | Bump to 1.6.0 version

Bump to 1.6.0

---

src/PullRequest/Application/CommandHandler/WelcomeNewContributorCommandHandler.php
tests/PullRequest/Application/CommandHandler/WelcomeNewContributorCommandHandlerTest.php

| Description?      | Add `ps-jarvis` to the excluded contributors list (for welcoming new contributors)<br/>(see https://github.com/PrestaShop/PrestaShop/pull/36340)
| Type?             | bug fix

Add ps-jarvis to excluded contributors for welcoming new contributors

---

src/PullRequest/Infrastructure/Adapter/RestPullRequestRepository.php
src/Shared/Infrastructure/Adapter/RestGithubCommitterRepository.php
templates/pr_comments/welcome.html.twig

| Description?      | Improve Welcome new contributor comment (see screenshot below table)<br/> and fix the way to check new contributors in repository.

Improve WelcomeNewContributorCommand

---

config/services.php

| Description?      | Bump to `1.7.0` version

Bump to `1.7.0` version

---

src/PullRequest/Domain/Aggregate/PullRequest/PullRequestDescription.php
tests/PullRequest/Application/CommandHandler/CheckTableDescriptionCommandHandlerTest.php

| Description?      | Add `~` for `Fixed issue or discussion` in PR table description to bypass the linked issues needed rule.<br>(For instance: https://github.com/PrestaShop/PrestaShop/pull/36357)

Improve check table description

---

config/services.php

| Description?      | Bump to `1.7.1`

Bump version to 1.7.1

---

src/PullRequest/Application/CommandHandler/CheckMilestoneCommandHandler.php
src/PullRequest/Domain/Gateway/PullRequestRepositoryInterface.php
src/PullRequest/Infrastructure/Adapter/InMemoryPullRequestRepository.php
src/PullRequest/Infrastructure/Adapter/RestPullRequestRepository.php
src/Shared/Infrastructure/Factory/CommandFactory/Strategy/Command/PullRequestLabeledStrategy.php
src/Shared/Infrastructure/Factory/CommandFactory/Strategy/Command/PullRequestMergedStrategy.php
templates/pr_comments/missing_milestone.html.twig
tests/PullRequest/Application/CommandHandler/CheckMilestoneCommandHandlerTest.php
tests/Shared/Infrastructure/Webhook/GithubWebhookTest.php

| Description?      | This command must be only execute on merge and not when we add a label on PR.<br>We don't check anymore the QA status on the PR. (Few PR can bypass this review)<br>We need to make this check for all repositories et not only on PrestaShop/PrestaShop.

Improve CheckMilestoneCommand

---

config/services.php

| Description?      | Bump to `1.8.0`
| Sponsor company   | PrestaShopSA

Bump to `1.8.0`

---

src/PullRequest/Domain/Aggregate/PullRequest/PullRequest.php
src/PullRequest/Domain/Aggregate/PullRequest/PullRequestDescription.php
tests/PullRequest/Application/CommandHandler/CheckTableDescriptionCommandHandlerTest.php
tests/Shared/Infrastructure/Provider/TranslationsCatalogProviderTest.php

| Description?      | Copy of https://github.com/PrestaShop/kanbanbot/pull/53 but not from a fork
| How to test?      | CI should be green

Acknowledge PS 8.2.x - copy of #53

---

config/services.php

| Description?      | Bump to 1.9.1
| How to test?      | ~

Bump to 1.9.1

---

src/PullRequest/Domain/Aggregate/PullRequest/PullRequest.php
src/PullRequest/Domain/Aggregate/PullRequest/PullRequestDescription.php
tests/PullRequest/Application/CommandHandler/CheckTableDescriptionCommandHandlerTest.php
tests/Shared/Infrastructure/Provider/TranslationsCatalogProviderTest.php

| Description?      | Please be specific when describing this change. What did you change? Why?
| How to test?      | CI green

Add new version in kanbanbot

---

config/services.php

| Description?      | Bump to `1.9.2`
| How to test?      | CI 🟢 only!

Bump to `1.9.2`

---

config/services.php

| Description?      | This PR exclude [open-source repository](https://github.com/PrestaShop/open-source/) to avoid Jarvis to do some silly things like [in this PR](https://github.com/PrestaShop/open-source/pull/274) with `Waiting for QA` label.
| Sponsor company   | Your company or customer's name goes here (if applicable).

Exclude open-source repository

---

config/services.php

| Description?      | Bump to `1.9.3`
| How to test?      | ~

Bump to `1.9.3`

---

config/services.php

| Description?      | Bump to 1.10.0

Bump to 1.10.0

---

.github/workflows/php.yml
.github/workflows/tests.yml

| Description?      | Fix github actions for the ci

Fix github actions for the ci

---

src/PullRequest/Application/CommandHandler/CheckHookCommandHandler.php
tests/PullRequest/Application/CommandHandler/CheckHookCommandHandlerTest.php

| Description?      | Avoid check hooks contribution on merge PR + adding tests

Avoid check hooks contribution on merge PR

---

config/services.php

| Description?      | Bump to v1.10.1.<br>This version is ready for production!
| How to test?      | CI ✅

Bump to v1.10.1
